Future task one
archykins/TodoApp pull request #1
Opened 2023-01-27 12:47 UTC by archykins

2023-01-29 08:29 UTC, Alexandr-Prokin requested changes
Не привязывай элементы к низу контейнера

2023-01-29 08:29 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        tools:ignore="MissingConstraints" />
удаляем, нужно сделать привязку к контейнеру

2023-01-29 08:29 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="385dp"
к низу не нужно привязывать

2023-01-29 08:29 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        tools:ignore="MissingConstraints" />
удаляем

2023-01-29 08:29 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="549dp"
удаляем

2023-01-29 08:29 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:minWidth="280dp"
удаляем

2023-01-29 08:29 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:lineHeight="20dp"
удаляем

2023-01-29 08:29 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:minHeight="48dp"
удаляем

2023-01-29 08:29 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +    <com.google.android.material.textfield.TextInputEditText
Этот элемент должен быть вложен в TextInputLayout

2023-01-29 08:29 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="77dp"
удаляем

2023-01-29 08:29 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:gravity="center_horizontal|top"
если убрать атрибут, что то изменится?

2023-01-29 18:56 UTC, archykins commented on app/src/main/res/layout/activity_main.xml
> +        android:gravity="center_horizontal|top"
если убрать, то у текста будет выравнивание по правому краю

2023-01-31 18:22 UTC, Alexandr-Prokin requested changes

2023-01-31 18:22 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="260dp"
Точные размеры убираем

2023-01-31 18:22 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="141dp"
точные размеры убираем

2023-01-31 18:22 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="309dp"
Тут тоже убираем точные размеры

2023-02-01 18:08 UTC, Alexandr-Prokin requested changes
Чуть чуть не по макету
<img width="874" alt="Снимок экрана 2023-02-01 в 21 07 16" src="https://user-images.githubusercontent.com/35171601/216126789-5b9e4502-122e-46fb-b1cc-2bebdd9a97dc.png">

2023-02-01 18:11 UTC, archykins commented
> Чуть чуть не по макету <img alt="Снимок экрана 2023-02-01 в 21 07 16" width="874" src="https://user-images.githubusercontent.com/35171601/216126789-5b9e4502-122e-46fb-b1cc-2bebdd9a97dc.png">

у меня просто не хочет работать эмулятор, поэтому не вижу окончательный результат((

2023-02-03 16:26 UTC, merged